# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20170428_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.ContractTemplate'),
        ),
    ]
