# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20170430_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together=set([('course_record', 'student')]),
        ),
    ]
