# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20170430_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
